# Generated by Django 4.2.6 on 2023-11-26 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('nomDoc', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Tipo de documento')),
                ('descDoc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion')),
                ('creaDoc', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actuDoc', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsr', models.CharField(max_length=12, unique=True, verbose_name='Cédula')),
                ('dirUsr', models.CharField(max_length=200, verbose_name='Dirección')),
                ('fnacUsr', models.DateField(blank=True, null=True, verbose_name='Fecha de Cumpleaños')),
                ('telUsr', models.CharField(blank=True, max_length=10, null=True, verbose_name='Num. Celular')),
                ('picUsr', models.ImageField(blank=True, default='null', null=True, upload_to='usuario', verbose_name='Imagen')),
                ('pubUsr', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('creaUsr', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actuUsr', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tipoDoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.tipodoc', verbose_name='Tipo de Documento')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
