# Generated by Django 4.2.6 on 2023-11-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DtaCategorias', '0001_initial'),
        ('DtaEmpresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idOfer', models.CharField(auto_created=True, max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('titOfer', models.CharField(max_length=200, verbose_name='Titulo Oferta')),
                ('cargoOfer', models.CharField(max_length=100, verbose_name='Cargo')),
                ('descOfer', models.CharField(max_length=200, verbose_name='Descripción Oferta')),
                ('salOfer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Salario')),
                ('pubOfer', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('creaOfer', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actuOfer', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('catOfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DtaCategorias.categorias', verbose_name='Categoria')),
                ('idEmpOfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DtaEmpresas.empresas', verbose_name='NIT Empresa')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
