# Generated by Django 4.2.6 on 2023-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DtaOfertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertas',
            name='contOfer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='skillOfer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Requerimientos'),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='ubcOfer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='descOfer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Oferta'),
        ),
    ]
