# Generated by Django 4.2.6 on 2023-11-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DtaOfertas', '0002_ofertas_contofer_ofertas_skillofer_ofertas_ubcofer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='idOfer',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
