# Generated by Django 4.2.6 on 2023-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DtaOfertas', '0003_alter_ofertas_idofer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='descOfer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción Oferta'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='skillOfer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Requerimientos'),
        ),
    ]
