# Generated by Django 4.2.6 on 2023-11-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DtaOfertas', '0004_alter_ofertas_descofer_alter_ofertas_skillofer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='descOfer',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción Oferta'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='skillOfer',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Requerimientos'),
        ),
    ]
