# Generated by Django 4.2.6 on 2023-11-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('idAlu', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Num. documento')),
                ('nomAlu', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apeAlu', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('carAlu', models.CharField(max_length=200, verbose_name='Carrera')),
                ('semAlu', models.CharField(max_length=10, verbose_name='Semestre')),
                ('pubAlu', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('creaAlu', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actuAlu', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
