# Generated by Django 4.2.6 on 2023-11-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DtaOfertas', '0001_initial'),
        ('DtaAlumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplica',
            fields=[
                ('idApp', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('stsApp', models.CharField(max_length=200, verbose_name='Estatus de la aplicación')),
                ('creaApp', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actuApp', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('idAluApp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DtaAlumnos.alumnos', verbose_name='Id de Alumno')),
                ('idOferApp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DtaOfertas.ofertas', verbose_name='Id de Oferta')),
            ],
            options={
                'verbose_name': 'Aplicacion',
                'verbose_name_plural': 'Aplicaciones',
            },
        ),
    ]
