# Generated by Django 4.2.6 on 2023-11-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DtaAplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplica',
            name='idApp',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
