# Generated by Django 4.2.6 on 2023-11-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCat', models.CharField(auto_created=True, max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('nomCat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('desCat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('pubCat', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('creaCat', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actuCat', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
